####################################################
#                                                  #
#                |   MY_PROJECT  |                 #
#                                                  #
####################################################

#Contact with me:
#
#VK: vk.com/deelter
#TWITTER: twitter.com/roma200315
#YOUTUBE: youtube.com/channel/UCRACU2JfOfClrlEHImv5pYw
#GITHUB: github.com/DeelTer
#
#DISCORD: DeelTer#4782

debug: true